services:
  - type: web
    name: healthnexus-api
    runtime: node
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: PORT
        value: 8080
      - key: NODE_ENV
        value: production
      - key: GEMINI_API_KEY
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRE
        value: 24h
      - key: JWT_REFRESH_EXPIRE
        value: 7d
